
Error: dbConnect: Error opening db 'mongodb://localhost:27017/ArtefactsJS': MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/home/jk/code/dist-app3/node_modules/mongodb-core/lib/topologies/server.js:564:11)
    at Pool.emit (events.js:182:13)
    at Connection.<anonymous> (/home/jk/code/dist-app3/node_modules/mongodb-core/lib/connection/pool.js:317:12)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (/home/jk/code/dist-app3/node_modules/mongodb-core/lib/connection/connection.js:246:50)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
From previous event:
    at NativeConnection.Connection.openUri (/home/jk/code/dist-app3/node_modules/mongoose/lib/connection.js:509:19)
    at Mongoose.connect (/home/jk/code/dist-app3/node_modules/mongoose/lib/index.js:236:15)
    at Object.dbConnect (/home/jk/code/dist-app3/app.js:23:36)
    at Object.wrapper [as dbConnect] (/home/jk/code/dist-app3/node_modules/lodash/lodash.js:4935:19)
    at main (/home/jk/code/dist-app3/index-jobs.js:52:13)
    at Object.<anonymous> (/home/jk/code/dist-app3/index-jobs.js:74:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
    at Object.onError (/home/jk/code/dist-app3/app.js:135:10)
    at Object.wrapper [as onError] (/home/jk/code/dist-app3/node_modules/lodash/lodash.js:4935:19)
    at Object.dbConnect (/home/jk/code/dist-app3/app.js:28:8)
    at process._tickCallback (internal/process/next_tick.js:68:7)

